# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

inverse_cpp <- function(objs) {
    .Call('_DPTM_inverse_cpp', PACKAGE = 'DPTM', objs)
}

lag_transform <- function(objs, t, n, lag, top) {
    .Call('_DPTM_lag_transform', PACKAGE = 'DPTM', objs, t, n, lag, top)
}

three_one <- function(pars1, delty0, evs, omega, cd, tt, nn, ny, varv1) {
    .Call('_DPTM_three_one', PACKAGE = 'DPTM', pars1, delty0, evs, omega, cd, tt, nn, ny, varv1)
}

three_oneb <- function(pars1, delty0, evs, omega, cd, tt, nn, ny, varv1) {
    .Call('_DPTM_three_oneb', PACKAGE = 'DPTM', pars1, delty0, evs, omega, cd, tt, nn, ny, varv1)
}

three_two <- function(pars1, delty0, evs, omega, cd, tt, nn) {
    .Call('_DPTM_three_two', PACKAGE = 'DPTM', pars1, delty0, evs, omega, cd, tt, nn)
}

